services:
    multi-agents-devcontainer:
        image: multi-agents-devcontainer
        container_name: multi-agents-devcontainer
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ..:/workspace:cached
        # This keeps the devcontainer running.
        entrypoint: ["tail", "-f", "/dev/null"]
        networks:
            - multi-agents

networks:
    multi-agents:
        name: multi-agents
        driver: bridge
